### ISSUE TITLE
Variable d'env

### ISSUE THREAD

**Issue by swotex** [ltuffery/minishell#20]
La variable d'environement doit renvoyer le '$' si une erreur dans l'ecriture de la var (si apres le '$' il y a autre chose qu'un alpha et '_' (pas de num))

**Comment by ltuffery** [comment]
fix avec 3c77d380c45431137701872cd16e68aee358cc56

**Comment by swotex** [comment]
**echo $'HOLA'** doit renvoyer **HOLA** nous on renvoi **$HOLLA**
**echo $""** -> rien nous -> $

**Comment by ltuffery** [comment]
Nouveau probleme qui est **echo $" no   no" yo** qui font ne revoie pas ` no   no yo` mais `no no yo` a cause de la fonction `is_ambigous()`
