### ISSUE TITLE
exit avec parametre 

### ISSUE THREAD

**Issue by swotex** [ltuffery/minishell#27]
```exit -1```
```exit more_long_long```
exit doit fonctionner avec des nombres négatifs
exit doit renvoyer une erreur lorsque le nombre dépasse un long long int (et exit ensuite)

**Comment by ltuffery** [comment]
fix le `exit -1`
et tentative pour le `exit more_long_long`
https://github.com/ltuffery/minishell/commit/5d88daf23e99dbc66d546d52e873a290eeefe2cd
