### ISSUE TITLE
Manque parsing

### ISSUE THREAD

**Issue by swotex** [ltuffery/minishell#4]
Il manque du parsing pour la redirection input/output file. (< et >).
par exemple : 
**> > outfile** - > syntax error near unexpected token '>'
**echo coucou > >out | echo nice** -> aucune des deux commande n'est exécuté, aucun fichier créer. -> Parsing.
Même soucis pour le infile **< < infile cat -e** -> syntax error near unexpected token '>'
Egalement il faut gérer qu'il n'y ai rien apres **cat >**

**Comment by ltuffery** [comment]
Bon a refaire
